### ISSUE TITLE
pgsu always writes to stderr, and this cannot be suppressed

### ISSUE THREAD

**Issue by jbweston** [aiidateam/pgsu#29]
When using functionality from pgsu in a Jupyter notebook I always get messages like the following printed to stderr:

```
Trying to become 'postgres' user. You may be asked for your 'sudo' password.                                              
could not change directory to "..../code/aiida-dynamic-workflows": Permission denied
```

These messages cannot be suppressed with `contextlib.redirect_stderr`, and there is no pgsu setting that I am aware of to suppress these messages.

AFAIK this happens here: https://github.com/aiidateam/pgsu/blob/master/pgsu/__init__.py#L294

we explicitly set the `stderr` of a subprocess to `subprocess.STDOUT`, which does not respect any reassignments to `sys.stdout` (e.g. by the `redirect_stderr` context manager). This is expected and documented behaviour of the `subprocess` module.

Would it be possible to have stderr redirected to a log, so that it may be managed with standard logging infra?

**Comment by ltalirz** [comment]
Absolutely! Would you be able to make a small PR?

Happy to review and release asap

**Comment by ltalirz** [comment]
fixed by https://github.com/aiidateam/pgsu/pull/30
